<script setup>
defineProps({
  name: String,
  selections: String,
  combo: String,
});

const a = {
  Event: {
    FeedId: 12,
    EventId: "8280658",
    ParentEventId: null,
    TypeValue: 2,
    BettingLayoutEnumValue: 0,
    TypeName: "PlatinumHounds",
    SubTypeName: "None",
    StartDateTimeAsWords: "2025/08/27 20:21:00",
    StartTimeAsWords: "20:21",
    FinishTimeAsWords: "20:21",
    Race: {
      Name: "Crawford Park (Night)",
      PlacePaysOn: 2,
      Distance: 720,
      Entries: [
        {
          FeedId: 335,
          Draw: 1,
          Name: "Mandolin Gin",
          Finish: null,
          Form: "4,6,5,6,7",
          LBW: "3.6;4.2;5.3;5.9;5.6",
          StarRating: 49,
          RacesSinceWin: 6,
          RacesSincePlace: 6,
          WinOdds: 8.7,
          PlaceOdds: 3.32,
          ShowOdds: 0,
          SecondOdds: 0,
          ThirdOdds: 0,
          LastOdds: 0,
          Last3Odds: 0,
          Gender: null,
          Age: null,
          SilkImagePath: null,
          SilkNumber: "23",
          DisplayFinish: 99,
          LBWAsArray: [3.6, 4.2, 5.3, 5.9, 5.6],
          InverseRating: 39,
          Description: "1. Mandolin Gin",
          Favorite: null,
          BallAllocations: null,
          BallsDrawn: null,
          ID: 335,
          HasErrorOccured: false,
          ErrorMessage: null,
        },
        {
          FeedId: 102,
          Draw: 2,
          Name: "Deliverance Boy",
          Finish: null,
          Form: "1,1,1,2,3",
          LBW: "0;0;0;0.8;1.9",
          StarRating: 68,
          RacesSinceWin: 2,
          RacesSincePlace: 1,
          WinOdds: 3.25,
          PlaceOdds: 1.86,
          ShowOdds: 0,
          SecondOdds: 0,
          ThirdOdds: 0,
          LastOdds: 0,
          Last3Odds: 0,
          Gender: null,
          Age: null,
          SilkImagePath: null,
          SilkNumber: "07",
          DisplayFinish: 99,
          LBWAsArray: [0, 0, 0, 0.8, 1.9],
          InverseRating: 15,
          Description: "2. Deliverance Boy",
          Favorite: 2,
          BallAllocations: null,
          BallsDrawn: null,
          ID: 102,
          HasErrorOccured: false,
          ErrorMessage: null,
        },
        {
          FeedId: 593,
          Draw: 3,
          Name: "Albany Jones",
          Finish: null,
          Form: "6,3,2,8,1",
          LBW: "4.6;1.8;0.7;7.5;0",
          StarRating: 39,
          RacesSinceWin: 0,
          RacesSincePlace: 0,
          WinOdds: 17.29,
          PlaceOdds: 5.09,
          ShowOdds: 0,
          SecondOdds: 0,
          ThirdOdds: 0,
          LastOdds: 0,
          Last3Odds: 0,
          Gender: null,
          Age: null,
          SilkImagePath: null,
          SilkNumber: "40",
          DisplayFinish: 99,
          LBWAsArray: [4.6, 1.8, 0.7, 7.5, 0],
          InverseRating: 51,
          Description: "3. Albany Jones",
          Favorite: null,
          BallAllocations: null,
          BallsDrawn: null,
          ID: 593,
          HasErrorOccured: false,
          ErrorMessage: null,
        },
        {
          FeedId: 39,
          Draw: 4,
          Name: "Houston",
          Finish: null,
          Form: "2,2,5,1,1",
          LBW: "0.9;1.1;3.9;0;0",
          StarRating: 76,
          RacesSinceWin: 0,
          RacesSincePlace: 0,
          WinOdds: 2.43,
          PlaceOdds: 1.6,
          ShowOdds: 0,
          SecondOdds: 0,
          ThirdOdds: 0,
          LastOdds: 0,
          Last3Odds: 0,
          Gender: null,
          Age: null,
          SilkImagePath: null,
          SilkNumber: "03",
          DisplayFinish: 99,
          LBWAsArray: [0.9, 1.1, 3.9, 0, 0],
          InverseRating: 5,
          Description: "4. Houston",
          Favorite: 1,
          BallAllocations: null,
          BallsDrawn: null,
          ID: 39,
          HasErrorOccured: false,
          ErrorMessage: null,
        },
        {
          FeedId: 239,
          Draw: 5,
          Name: "Simply Sensational",
          Finish: null,
          Form: "4,4,3,4,4",
          LBW: "3.1;3.4;1.8;3.0;5.1",
          StarRating: 49,
          RacesSinceWin: 7,
          RacesSincePlace: 7,
          WinOdds: 5.96,
          PlaceOdds: 2.64,
          ShowOdds: 0,
          SecondOdds: 0,
          ThirdOdds: 0,
          LastOdds: 0,
          Last3Odds: 0,
          Gender: null,
          Age: null,
          SilkImagePath: null,
          SilkNumber: "16",
          DisplayFinish: 99,
          LBWAsArray: [3.1, 3.4, 1.8, 3, 5.1],
          InverseRating: 39,
          Description: "5. Simply Sensational",
          Favorite: 3,
          BallAllocations: null,
          BallsDrawn: null,
          ID: 239,
          HasErrorOccured: false,
          ErrorMessage: null,
        },
        {
          FeedId: 462,
          Draw: 6,
          Name: "Vespa Lindt",
          Finish: null,
          Form: "4,5,3,4,2",
          LBW: "3.1;5.0;3.5;2.9;1.8",
          StarRating: 41,
          RacesSinceWin: 10,
          RacesSincePlace: 0,
          WinOdds: 13.02,
          PlaceOdds: 4.25,
          ShowOdds: 0,
          SecondOdds: 0,
          ThirdOdds: 0,
          LastOdds: 0,
          Last3Odds: 0,
          Gender: null,
          Age: null,
          SilkImagePath: null,
          SilkNumber: "31",
          DisplayFinish: 99,
          LBWAsArray: [3.1, 5, 3.5, 2.9, 1.8],
          InverseRating: 49,
          Description: "6. Vespa Lindt",
          Favorite: null,
          BallAllocations: null,
          BallsDrawn: null,
          ID: 462,
          HasErrorOccured: false,
          ErrorMessage: null,
        },
      ],
      Result: null,
      KenoFeedID: 0,
      KenoResult: null,
      NoOfParticipants: null,
      ID: 0,
      HasErrorOccured: false,
      ErrorMessage: null,
    },
    Boxing: null,
    PlayerVsPlayer: null,
    Archery: null,
    FootballMatch: null,
    FootballTournamentMatch: null,
    RacingRouletteV2: null,
    SpinAndWin: null,
    FootballLeagueWeek: null,
    IceHockeyMatch: null,
    FinalHoopsMatch: null,
    PrimaryMarkets: [
      {
        FeedId: "Win",
        Name: "Win",
        Abbreviation: null,
        ClassValue: 1,
        ArcherySelections: [],
        BoxingSelections: [],
        InstantBetSelections: [],
        PlayerVsPlayerSelections: [],
        FootballMatchSelections: [],
        KenoSelections: [],
        LuckyLoot624Selections: [],
        RaceSelections: [
          {
            First: 1,
            Second: null,
            Third: null,
            FeedId: "1",
            Odds: 8.7,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "1. Mandolin Gin",
            DisplayDescription: "1. Mandolin Gin",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 2,
            Second: null,
            Third: null,
            FeedId: "2",
            Odds: 3.25,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "2. Deliverance Boy",
            DisplayDescription: "2. Deliverance Boy",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 3,
            Second: null,
            Third: null,
            FeedId: "3",
            Odds: 17.29,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "3. Albany Jones",
            DisplayDescription: "3. Albany Jones",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 4,
            Second: null,
            Third: null,
            FeedId: "4",
            Odds: 2.43,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "4. Houston",
            DisplayDescription: "4. Houston",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 5,
            Second: null,
            Third: null,
            FeedId: "5",
            Odds: 5.96,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "5. Simply Sensational",
            DisplayDescription: "5. Simply Sensational",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 6,
            Second: null,
            Third: null,
            FeedId: "6",
            Odds: 13.02,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "6. Vespa Lindt",
            DisplayDescription: "6. Vespa Lindt",
            ExtraDescription: "",
            EntryID: null,
          },
        ],
        RacingRouletteSelections: [],
        SpinAndWinSelections: [],
        IceHockeyMatchSelections: [],
        FinalHoopsMatchSelections: [],
        CricketMatchSelections: [],
        MarketClassSelections: [],
        FootballTournamentMatchSelections: [],
        LuckyRacingSelections: [],
        AnimalitosSelections: [],
        Split: null,
        IsClassAvailableForBetting: true,
        IsClassParticipants: true,
        ClassEnumValue: "Win",
        MarketClassID: 1,
        DisplayDescription: "Win",
        AmericanDisplayDescription: null,
        CssClass: null,
        BettingLayouts: [
          {
            EventTypeEnumValue: 2,
            MarketClassEventTypeID: 0,
            Position: 1,
            IsExpanded: false,
            BettingLayoutEnumValue: 1,
            MarketClassID: 1,
            ParentEventTypeEnumValue: null,
            LayoutPattern: null,
          },
        ],
        WinningSelectionID: null,
        WinningSelectionDescription: null,
        ResourceKey: "Win",
        ID: "12-2-8280658-1",
        HasErrorOccured: false,
        ErrorMessage: null,
      },
      {
        FeedId: "Place",
        Name: "Place",
        Abbreviation: null,
        ClassValue: 2,
        ArcherySelections: [],
        BoxingSelections: [],
        InstantBetSelections: [],
        PlayerVsPlayerSelections: [],
        FootballMatchSelections: [],
        KenoSelections: [],
        LuckyLoot624Selections: [],
        RaceSelections: [
          {
            First: 1,
            Second: null,
            Third: null,
            FeedId: "1",
            Odds: 3.32,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "1. Mandolin Gin",
            DisplayDescription: "1. Mandolin Gin",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 2,
            Second: null,
            Third: null,
            FeedId: "2",
            Odds: 1.86,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "2. Deliverance Boy",
            DisplayDescription: "2. Deliverance Boy",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 3,
            Second: null,
            Third: null,
            FeedId: "3",
            Odds: 5.09,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "3. Albany Jones",
            DisplayDescription: "3. Albany Jones",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 4,
            Second: null,
            Third: null,
            FeedId: "4",
            Odds: 1.6,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "4. Houston",
            DisplayDescription: "4. Houston",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 5,
            Second: null,
            Third: null,
            FeedId: "5",
            Odds: 2.64,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "5. Simply Sensational",
            DisplayDescription: "5. Simply Sensational",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 6,
            Second: null,
            Third: null,
            FeedId: "6",
            Odds: 4.25,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "6. Vespa Lindt",
            DisplayDescription: "6. Vespa Lindt",
            ExtraDescription: "",
            EntryID: null,
          },
        ],
        RacingRouletteSelections: [],
        SpinAndWinSelections: [],
        IceHockeyMatchSelections: [],
        FinalHoopsMatchSelections: [],
        CricketMatchSelections: [],
        MarketClassSelections: [],
        FootballTournamentMatchSelections: [],
        LuckyRacingSelections: [],
        AnimalitosSelections: [],
        Split: null,
        IsClassAvailableForBetting: true,
        IsClassParticipants: false,
        ClassEnumValue: "Place",
        MarketClassID: 2,
        DisplayDescription: "Place",
        AmericanDisplayDescription: null,
        CssClass: null,
        BettingLayouts: [
          {
            EventTypeEnumValue: 2,
            MarketClassEventTypeID: 0,
            Position: 2,
            IsExpanded: false,
            BettingLayoutEnumValue: 1,
            MarketClassID: 2,
            ParentEventTypeEnumValue: null,
            LayoutPattern: null,
          },
        ],
        WinningSelectionID: null,
        WinningSelectionDescription: null,
        ResourceKey: "Place",
        ID: "12-2-8280658-2",
        HasErrorOccured: false,
        ErrorMessage: null,
      },
    ],
    PrimaryMarketsStore: [],
    Markets: [
      {
        FeedId: "Win",
        Name: "Win",
        Abbreviation: null,
        ClassValue: 1,
        ArcherySelections: [],
        BoxingSelections: [],
        InstantBetSelections: [],
        PlayerVsPlayerSelections: [],
        FootballMatchSelections: [],
        KenoSelections: [],
        LuckyLoot624Selections: [],
        RaceSelections: [
          {
            First: 1,
            Second: null,
            Third: null,
            FeedId: "1",
            Odds: 8.7,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "1. Mandolin Gin",
            DisplayDescription: "1. Mandolin Gin",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 2,
            Second: null,
            Third: null,
            FeedId: "2",
            Odds: 3.25,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "2. Deliverance Boy",
            DisplayDescription: "2. Deliverance Boy",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 3,
            Second: null,
            Third: null,
            FeedId: "3",
            Odds: 17.29,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "3. Albany Jones",
            DisplayDescription: "3. Albany Jones",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 4,
            Second: null,
            Third: null,
            FeedId: "4",
            Odds: 2.43,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "4. Houston",
            DisplayDescription: "4. Houston",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 5,
            Second: null,
            Third: null,
            FeedId: "5",
            Odds: 5.96,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "5. Simply Sensational",
            DisplayDescription: "5. Simply Sensational",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 6,
            Second: null,
            Third: null,
            FeedId: "6",
            Odds: 13.02,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "6. Vespa Lindt",
            DisplayDescription: "6. Vespa Lindt",
            ExtraDescription: "",
            EntryID: null,
          },
        ],
        RacingRouletteSelections: [],
        SpinAndWinSelections: [],
        IceHockeyMatchSelections: [],
        FinalHoopsMatchSelections: [],
        CricketMatchSelections: [],
        MarketClassSelections: [],
        FootballTournamentMatchSelections: [],
        LuckyRacingSelections: [],
        AnimalitosSelections: [],
        Split: null,
        IsClassAvailableForBetting: true,
        IsClassParticipants: true,
        ClassEnumValue: "Win",
        MarketClassID: 1,
        DisplayDescription: "Win",
        AmericanDisplayDescription: null,
        CssClass: null,
        BettingLayouts: [
          {
            EventTypeEnumValue: 2,
            MarketClassEventTypeID: 0,
            Position: 1,
            IsExpanded: false,
            BettingLayoutEnumValue: 1,
            MarketClassID: 1,
            ParentEventTypeEnumValue: null,
            LayoutPattern: null,
          },
        ],
        WinningSelectionID: null,
        WinningSelectionDescription: null,
        ResourceKey: "Win",
        ID: "12-2-8280658-1",
        HasErrorOccured: false,
        ErrorMessage: null,
      },
      {
        FeedId: "Place",
        Name: "Place",
        Abbreviation: null,
        ClassValue: 2,
        ArcherySelections: [],
        BoxingSelections: [],
        InstantBetSelections: [],
        PlayerVsPlayerSelections: [],
        FootballMatchSelections: [],
        KenoSelections: [],
        LuckyLoot624Selections: [],
        RaceSelections: [
          {
            First: 1,
            Second: null,
            Third: null,
            FeedId: "1",
            Odds: 3.32,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "1. Mandolin Gin",
            DisplayDescription: "1. Mandolin Gin",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 2,
            Second: null,
            Third: null,
            FeedId: "2",
            Odds: 1.86,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "2. Deliverance Boy",
            DisplayDescription: "2. Deliverance Boy",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 3,
            Second: null,
            Third: null,
            FeedId: "3",
            Odds: 5.09,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "3. Albany Jones",
            DisplayDescription: "3. Albany Jones",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 4,
            Second: null,
            Third: null,
            FeedId: "4",
            Odds: 1.6,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "4. Houston",
            DisplayDescription: "4. Houston",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 5,
            Second: null,
            Third: null,
            FeedId: "5",
            Odds: 2.64,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "5. Simply Sensational",
            DisplayDescription: "5. Simply Sensational",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: 6,
            Second: null,
            Third: null,
            FeedId: "6",
            Odds: 4.25,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "6. Vespa Lindt",
            DisplayDescription: "6. Vespa Lindt",
            ExtraDescription: "",
            EntryID: null,
          },
        ],
        RacingRouletteSelections: [],
        SpinAndWinSelections: [],
        IceHockeyMatchSelections: [],
        FinalHoopsMatchSelections: [],
        CricketMatchSelections: [],
        MarketClassSelections: [],
        FootballTournamentMatchSelections: [],
        LuckyRacingSelections: [],
        AnimalitosSelections: [],
        Split: null,
        IsClassAvailableForBetting: true,
        IsClassParticipants: false,
        ClassEnumValue: "Place",
        MarketClassID: 2,
        DisplayDescription: "Place",
        AmericanDisplayDescription: null,
        CssClass: null,
        BettingLayouts: [
          {
            EventTypeEnumValue: 2,
            MarketClassEventTypeID: 0,
            Position: 2,
            IsExpanded: false,
            BettingLayoutEnumValue: 1,
            MarketClassID: 2,
            ParentEventTypeEnumValue: null,
            LayoutPattern: null,
          },
        ],
        WinningSelectionID: null,
        WinningSelectionDescription: null,
        ResourceKey: "Place",
        ID: "12-2-8280658-2",
        HasErrorOccured: false,
        ErrorMessage: null,
      },
      {
        FeedId: "OE",
        Name: "Odd/Even",
        Abbreviation: null,
        ClassValue: 134,
        ArcherySelections: [],
        BoxingSelections: [],
        InstantBetSelections: [],
        PlayerVsPlayerSelections: [],
        FootballMatchSelections: [],
        KenoSelections: [],
        LuckyLoot624Selections: [],
        RaceSelections: [
          {
            First: -1,
            Second: null,
            Third: null,
            FeedId: "O",
            Odds: 3.1,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "O",
            DisplayDescription: "Odd",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: -1,
            Second: null,
            Third: null,
            FeedId: "E",
            Odds: 1.31,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "E",
            DisplayDescription: "Even",
            ExtraDescription: "",
            EntryID: null,
          },
        ],
        RacingRouletteSelections: [],
        SpinAndWinSelections: [],
        IceHockeyMatchSelections: [],
        FinalHoopsMatchSelections: [],
        CricketMatchSelections: [],
        MarketClassSelections: [],
        FootballTournamentMatchSelections: [],
        LuckyRacingSelections: [],
        AnimalitosSelections: [],
        Split: null,
        IsClassAvailableForBetting: true,
        IsClassParticipants: false,
        ClassEnumValue: "RacingOddEven",
        MarketClassID: 134,
        DisplayDescription: "Odd/Even",
        AmericanDisplayDescription: null,
        CssClass: null,
        BettingLayouts: [
          {
            EventTypeEnumValue: 2,
            MarketClassEventTypeID: 0,
            Position: 5,
            IsExpanded: false,
            BettingLayoutEnumValue: 1,
            MarketClassID: 134,
            ParentEventTypeEnumValue: null,
            LayoutPattern: null,
          },
        ],
        WinningSelectionID: null,
        WinningSelectionDescription: null,
        ResourceKey: "RacingOddEven",
        ID: "12-2-8280658-134",
        HasErrorOccured: false,
        ErrorMessage: null,
      },
      {
        FeedId: "HL",
        Name: "High/Low",
        Abbreviation: null,
        ClassValue: 135,
        ArcherySelections: [],
        BoxingSelections: [],
        InstantBetSelections: [],
        PlayerVsPlayerSelections: [],
        FootballMatchSelections: [],
        KenoSelections: [],
        LuckyLoot624Selections: [],
        RaceSelections: [
          {
            First: -1,
            Second: null,
            Third: null,
            FeedId: "H",
            Odds: 1.59,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "H",
            DisplayDescription: "High",
            ExtraDescription: "",
            EntryID: null,
          },
          {
            First: -1,
            Second: null,
            Third: null,
            FeedId: "L",
            Odds: 2.17,
            IsWinner: false,
            Sort: 0,
            FeedDescription: "L",
            DisplayDescription: "Low",
            ExtraDescription: "",
            EntryID: null,
          },
        ],
        RacingRouletteSelections: [],
        SpinAndWinSelections: [],
        IceHockeyMatchSelections: [],
        FinalHoopsMatchSelections: [],
        CricketMatchSelections: [],
        MarketClassSelections: [],
        FootballTournamentMatchSelections: [],
        LuckyRacingSelections: [],
        AnimalitosSelections: [],
        Split: null,
        IsClassAvailableForBetting: true,
        IsClassParticipants: false,
        ClassEnumValue: "RacingHighLow",
        MarketClassID: 135,
        DisplayDescription: "High/Low",
        AmericanDisplayDescription: null,
        CssClass: null,
        BettingLayouts: [
          {
            EventTypeEnumValue: 2,
            MarketClassEventTypeID: 0,
            Position: 6,
            IsExpanded: false,
            BettingLayoutEnumValue: 1,
            MarketClassID: 135,
            ParentEventTypeEnumValue: null,
            LayoutPattern: null,
          },
        ],
        WinningSelectionID: null,
        WinningSelectionDescription: null,
        ResourceKey: "RacingHighLow",
        ID: "12-2-8280658-135",
        HasErrorOccured: false,
        ErrorMessage: null,
      },
      {
        FeedId: null,
        Name: null,
        Abbreviation: null,
        ClassValue: 3,
        ArcherySelections: [],
        BoxingSelections: [],
        InstantBetSelections: [],
        PlayerVsPlayerSelections: [],
        FootballMatchSelections: [],
        KenoSelections: [],
        LuckyLoot624Selections: [],
        RaceSelections: [],
        RacingRouletteSelections: [],
        SpinAndWinSelections: [],
        IceHockeyMatchSelections: [],
        FinalHoopsMatchSelections: [],
        CricketMatchSelections: [],
        MarketClassSelections: [],
        FootballTournamentMatchSelections: [],
        LuckyRacingSelections: [],
        AnimalitosSelections: [],
        Split: null,
        IsClassAvailableForBetting: true,
        IsClassParticipants: false,
        ClassEnumValue: "Forecast",
        MarketClassID: 3,
        DisplayDescription: "1st Two In Order",
        AmericanDisplayDescription: null,
        CssClass: null,
        BettingLayouts: [
          {
            EventTypeEnumValue: 2,
            MarketClassEventTypeID: 0,
            Position: 1,
            IsExpanded: false,
            BettingLayoutEnumValue: 1,
            MarketClassID: 3,
            ParentEventTypeEnumValue: null,
            LayoutPattern: null,
          },
        ],
        WinningSelectionID: null,
        WinningSelectionDescription: null,
        ResourceKey: "Forecast",
        ID: "12-2-8280658-3",
        HasErrorOccured: false,
        ErrorMessage: null,
      },
      {
        FeedId: null,
        Name: null,
        Abbreviation: null,
        ClassValue: 5,
        ArcherySelections: [],
        BoxingSelections: [],
        InstantBetSelections: [],
        PlayerVsPlayerSelections: [],
        FootballMatchSelections: [],
        KenoSelections: [],
        LuckyLoot624Selections: [],
        RaceSelections: [],
        RacingRouletteSelections: [],
        SpinAndWinSelections: [],
        IceHockeyMatchSelections: [],
        FinalHoopsMatchSelections: [],
        CricketMatchSelections: [],
        MarketClassSelections: [],
        FootballTournamentMatchSelections: [],
        LuckyRacingSelections: [],
        AnimalitosSelections: [],
        Split: null,
        IsClassAvailableForBetting: true,
        IsClassParticipants: false,
        ClassEnumValue: "Tricast",
        MarketClassID: 5,
        DisplayDescription: "1st Three In Order",
        AmericanDisplayDescription: null,
        CssClass: null,
        BettingLayouts: [
          {
            EventTypeEnumValue: 2,
            MarketClassEventTypeID: 0,
            Position: 3,
            IsExpanded: false,
            BettingLayoutEnumValue: 1,
            MarketClassID: 5,
            ParentEventTypeEnumValue: null,
            LayoutPattern: null,
          },
        ],
        WinningSelectionID: null,
        WinningSelectionDescription: null,
        ResourceKey: "Tricast",
        ID: "12-2-8280658-5",
        HasErrorOccured: false,
        ErrorMessage: null,
      },
      {
        FeedId: null,
        Name: null,
        Abbreviation: null,
        ClassValue: 4,
        ArcherySelections: [],
        BoxingSelections: [],
        InstantBetSelections: [],
        PlayerVsPlayerSelections: [],
        FootballMatchSelections: [],
        KenoSelections: [],
        LuckyLoot624Selections: [],
        RaceSelections: [],
        RacingRouletteSelections: [],
        SpinAndWinSelections: [],
        IceHockeyMatchSelections: [],
        FinalHoopsMatchSelections: [],
        CricketMatchSelections: [],
        MarketClassSelections: [],
        FootballTournamentMatchSelections: [],
        LuckyRacingSelections: [],
        AnimalitosSelections: [],
        Split: null,
        IsClassAvailableForBetting: true,
        IsClassParticipants: false,
        ClassEnumValue: "ReverseForecast",
        MarketClassID: 4,
        DisplayDescription: "1st Two Any Order",
        AmericanDisplayDescription: null,
        CssClass: null,
        BettingLayouts: [
          {
            EventTypeEnumValue: 2,
            MarketClassEventTypeID: 0,
            Position: 2,
            IsExpanded: false,
            BettingLayoutEnumValue: 1,
            MarketClassID: 4,
            ParentEventTypeEnumValue: null,
            LayoutPattern: null,
          },
        ],
        WinningSelectionID: null,
        WinningSelectionDescription: null,
        ResourceKey: "ReverseForecast",
        ID: "12-2-8280658-4",
        HasErrorOccured: false,
        ErrorMessage: null,
      },
      {
        FeedId: null,
        Name: null,
        Abbreviation: null,
        ClassValue: 6,
        ArcherySelections: [],
        BoxingSelections: [],
        InstantBetSelections: [],
        PlayerVsPlayerSelections: [],
        FootballMatchSelections: [],
        KenoSelections: [],
        LuckyLoot624Selections: [],
        RaceSelections: [],
        RacingRouletteSelections: [],
        SpinAndWinSelections: [],
        IceHockeyMatchSelections: [],
        FinalHoopsMatchSelections: [],
        CricketMatchSelections: [],
        MarketClassSelections: [],
        FootballTournamentMatchSelections: [],
        LuckyRacingSelections: [],
        AnimalitosSelections: [],
        Split: null,
        IsClassAvailableForBetting: true,
        IsClassParticipants: false,
        ClassEnumValue: "ReverseTricast",
        MarketClassID: 6,
        DisplayDescription: "1st Three Any Order",
        AmericanDisplayDescription: null,
        CssClass: null,
        BettingLayouts: [
          {
            EventTypeEnumValue: 2,
            MarketClassEventTypeID: 0,
            Position: 4,
            IsExpanded: false,
            BettingLayoutEnumValue: 1,
            MarketClassID: 6,
            ParentEventTypeEnumValue: null,
            LayoutPattern: null,
          },
        ],
        WinningSelectionID: null,
        WinningSelectionDescription: null,
        ResourceKey: "ReverseTricast",
        ID: "12-2-8280658-6",
        HasErrorOccured: false,
        ErrorMessage: null,
      },
      {
        FeedId: null,
        Name: null,
        Abbreviation: null,
        ClassValue: 133,
        ArcherySelections: [],
        BoxingSelections: [],
        InstantBetSelections: [],
        PlayerVsPlayerSelections: [],
        FootballMatchSelections: [],
        KenoSelections: [],
        LuckyLoot624Selections: [],
        RaceSelections: [],
        RacingRouletteSelections: [],
        SpinAndWinSelections: [],
        IceHockeyMatchSelections: [],
        FinalHoopsMatchSelections: [],
        CricketMatchSelections: [],
        MarketClassSelections: [],
        FootballTournamentMatchSelections: [],
        LuckyRacingSelections: [],
        AnimalitosSelections: [],
        Split: null,
        IsClassAvailableForBetting: true,
        IsClassParticipants: false,
        ClassEnumValue: "Swinger",
        MarketClassID: 133,
        DisplayDescription: "Swinger",
        AmericanDisplayDescription: null,
        CssClass: null,
        BettingLayouts: [
          {
            EventTypeEnumValue: 2,
            MarketClassEventTypeID: 0,
            Position: 5,
            IsExpanded: false,
            BettingLayoutEnumValue: 1,
            MarketClassID: 133,
            ParentEventTypeEnumValue: null,
            LayoutPattern: null,
          },
        ],
        WinningSelectionID: null,
        WinningSelectionDescription: null,
        ResourceKey: "Swinger",
        ID: "12-2-8280658-133",
        HasErrorOccured: false,
        ErrorMessage: null,
      },
    ],
    Events: null,
    AdjustedStartTime: "/Date(1756315260643)/",
    AdjustedFinishTime: "/Date(1756315315643)/",
    BetCloseTime: "/Date(1756315260643)/",
    Number: 2106,
    StatusValue: 1,
    IsFinished: false,
    FeedGuid: "00000000-0000-0000-0000-000000000000",
    CacheExpiryDate: null,
    CacheExpiryDateAsWords: "",
    EstimatedFinishTime: "/Date(1756315335643)/",
    IsNow: false,
    IsNext: false,
    HasBeenProcessed: false,
    GameProviderGUID: "00000000-0000-0000-0000-000000000000",
    IceHockeyLeagueWeek: null,
    FinalHoopsLeagueWeek: null,
    FootballTournamentLeagueWeek: null,
    CricketMatch: null,
    LuckyRacing: null,
    Animalitos: null,
    ID: "12-2-8280658",
    HasErrorOccured: false,
    ErrorMessage: null,
  },
};
</script>

<template>
  <div class="ComboPanel">
    <button
      class="flex flex-col items-center justify-center w-full xl:w-full text-center mb-1 px-[12px] lg:px-[6px] xl:px-[12px] py-[0px] text-sm text-white bg-[#09b517] border border-[#fcfcfc] rounded-[3px] shadow-[0_0_5px_rgba(55,179,74,0.4)] hover:border-transparent hover:shadow-[inset_0_0_6px_rgba(0,0,0,0.5),0_0_0_black] transition-all duration-400"
    >
      <span class="ml-1 text-[14px] font-bold px-[7px] py-[2px] uppercase">
        {{ name }}
      </span>
      <span class="text-[10.5px] font-semibold opacity-85">
        {{ selections }}
      </span>
      <span class="text-[10.5px] font-semibold opacity-85">
        {{ combo }} combination
      </span>
    </button>
  </div>
</template>
